module.exports = {
    ROBOT_NAME: '机器人小z',
    INIT_ROOM: 'Lvmoo',
    INIT_ROOM_INFO: '有问题欢迎提issue',
    INIT_ADMIN_EMAIL: 'kay',
    DEFAULT_AVATAR: 'https://cdn.lvmoo.com/chat/user.svg',
    DEFAULT_GROUP_AVATAR: 'https://cdn.lvmoo.com/chat/download.svg',
    DAY: 24*60*60*1000,
    JWT_KEY: 'JWT_KEY',
    ROBOT_URL: 'http://www.tuling123.com/openapi/api',
    ROBOT_KEY: '273e3ca4189a3fc03b4a94db8d87796b',
    ROBOT_AVATAR:'http://oajmk96un.bkt.clouddn.com/robot.jpg',
    QINIU_ACCESS_KEY: 'xxxxxxx',
    QINIU_SECRET_KEY: 'xxxxx',
    QINIU_CNAME: 'https://cdn.lvmoo.com',
    QINIU_BUCKET: 'wwww',
    MAX_ROOM: 5,
    MAX_BLOCK: 30,
}
